receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  awsemf:
    region: ${AWS_REGION:us-east-1}
  awsxray:
    region: ${AWS_REGION:us-east-1}

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsemf]

