receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  awsemf:
    region: ${AWS_REGION:us-east-1}
  awsxray:
    region: ${AWS_REGION:us-east-1}
  prometheusremotewrite:
    # Optional: send metrics to Amazon Managed Prometheus for long-term storage and dashboards via Amazon Managed Grafana
    endpoint: ${PROM_REMOTE_WRITE_ENDPOINT:}
    auth:
      authenticator: sigv4auth

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsemf]
    # For AMP (if configured)
    metrics/amp:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]

