global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'liveeventservice-api'
    static_configs:
      - targets: ['api:80']
    metrics_path: /metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']

