name: Security Testing

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
  schedule:
    # Weekly security scan (Sundays at midnight)
    - cron: '0 0 * * 0'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    # Run security audit for NuGet packages
    - name: Run NuGet security audit
      run: |
        dotnet list package --vulnerable --include-transitive

    # Run OWASP Dependency-Check
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'LiveEventService'
        path: './src'
        format: 'HTML'

    # Run SonarCloud analysis
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      continue-on-error: true

    # Upload security scan results
    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          **/dependency-check-report.html
          **/dependency-check-report.json

    # Run OWASP ZAP baseline scan (only on schedule)
    - name: Run OWASP ZAP baseline scan
      if: github.event_name == 'schedule'
      uses: zaproxy/action-baseline@v0.9.0
      with:
        target: 'https://yourapi.example.com' # Update with your API URL
        rules_file_name: 'zap.conf'
        cmd_options: '-I -j -m 5 -T 60 -z "-config api.disablekey=true"'

    # Check for secrets in code
    - name: Detect secrets in code
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .github/gitleaks.toml

    # Run .NET security code analysis with built-in tools
    - name: Run .NET Security Analysis
      run: |
        # Run security analyzers
        dotnet build --configuration Release --verbosity normal
        
        # Run any additional security checks here
        echo "Security analysis completed"
